# Generated by Django 5.0.1 on 2024-04-03 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='customer_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='contactform',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
