# Generated by Django 5.0.1 on 2024-04-03 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_contactform_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
