# Generated by Django 5.0.4 on 2024-04-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_alter_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
