# Generated by Django 5.0.4 on 2024-04-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_bilingform'),
    ]

    operations = [
        
        
        migrations.AddField(
            model_name='orders',
            name='Customer_name',
            field=models.CharField(default='demo', max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='product_name',
            field=models.CharField(default='demo', max_length=100),
        ),
    ]
